package hbn;
// Generated 20.11.2019 12:10:53 by Hibernate Tools 5.4.7.Final

/**
 * Kunde generated by hbm2java
 */
public class Kunde implements java.io.Serializable {

	private Integer id;
	private String vorname;
	private String nachname;
	private String username;
	private String passwort;
	private String email;

	public Kunde() {
	}

	public Kunde(String vorname, String nachname, String username, String passwort, String email) {
		this.vorname = vorname;
		this.nachname = nachname;
		this.username = username;
		this.passwort = passwort;
		this.email = email;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getVorname() {
		return this.vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}

	public String getNachname() {
		return this.nachname;
	}

	public void setNachname(String nachname) {
		this.nachname = nachname;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPasswort() {
		return this.passwort;
	}

	public void setPasswort(String passwort) {
		this.passwort = passwort;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
